apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipster-shop
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize/base
    repoURL: https://github.com/platform-proj/microservices-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true